### ISSUE TITLE
[BUG] Error while loading shared libraries: libhicops-core.so: cannot open shared object file: No such file or director

### ISSUE THREAD

**Issue by AP0LL0916** [pcdslab/gicops#14]
This error pops up everytime I try to run gicops on system restart or after a while. Ive found the solution to simply be to just set LD_Library environment variable again with 
export LD_LIBRARY_PATH=$gicops_PATH/lib:$LD_LIBRARY_PATH
and gicops should run again. A more permanent fix would be a script that automatically sets environment variables on startup if you are one to encounter this error

**Comment by mhaseeb123** [comment]
Hello, yes exactly you have found the correct solution. Adding the said export command to your `${HOME}/.bashrc` file would automatically load it for you every time you launch a new terminal.
